/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.blood_bank;

/**
 *
 * @author User 01
 */
public class Blood_Bank_HomePage extends javax.swing.JFrame {

    /**
     * Creates new form Blood_Bank_HomePage
     */
    
    boolean show_option, donate_option, recieve_option;
    public Blood_Bank_HomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        show = new javax.swing.JRadioButton();
        donate = new javax.swing.JRadioButton();
        recieve = new javax.swing.JRadioButton();
        hpb = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(425, 325));
        getContentPane().setLayout(null);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jLabel2.setText("Blood Bank");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 200, 60);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Dhanush Soma; Chandra");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(150, 0, 250, 30);

        buttonGroup1.add(show);
        show.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        show.setText("Show Data");
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });
        getContentPane().add(show);
        show.setBounds(0, 190, 160, 60);

        buttonGroup1.add(donate);
        donate.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        donate.setText("Donate Blood");
        donate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donateActionPerformed(evt);
            }
        });
        getContentPane().add(donate);
        donate.setBounds(0, 70, 160, 60);

        buttonGroup1.add(recieve);
        recieve.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        recieve.setText("Recieve Blood");
        recieve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recieveActionPerformed(evt);
            }
        });
        getContentPane().add(recieve);
        recieve.setBounds(0, 130, 160, 60);

        hpb.setText("Next>>");
        hpb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hpbActionPerformed(evt);
            }
        });
        getContentPane().add(hpb);
        hpb.setBounds(160, 250, 72, 22);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\dhanu\\OneDrive\\Desktop\\images_ccexpress.jpeg")); // NOI18N
        jLabel1.setInheritsPopupMenu(false);
        jLabel1.setPreferredSize(new java.awt.Dimension(400, 300));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-430, 0, 870, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        // TODO add your handling code here:
        show_option = true;
    }//GEN-LAST:event_showActionPerformed

    private void donateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donateActionPerformed
        // TODO add your handling code here:
        donate_option = true;
    }//GEN-LAST:event_donateActionPerformed
                                          
    private void recieveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recieveActionPerformed
        // TODO add your handling code here:
        recieve_option = true;
    }//GEN-LAST:event_recieveActionPerformed

    private void hpbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hpbActionPerformed
        // TODO add your handling code here:
        if(show_option){
        new Show_Information().setVisible(true);
        dispose();
        }else if(donate_option){
        new Donor_Information().setVisible(true);
        dispose();
        }else if(recieve_option){
        new Recipient_Information().setVisible(true);
        dispose();
        }
    }//GEN-LAST:event_hpbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Blood_Bank_HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Blood_Bank_HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Blood_Bank_HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Blood_Bank_HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Blood_Bank_HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton donate;
    private javax.swing.JButton hpb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton recieve;
    private javax.swing.JRadioButton show;
    // End of variables declaration//GEN-END:variables
}
