/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.blood_bank;

import java.sql.*;
import javax.swing.*;

/**
 *
 * @author User 01
 */
public class Donor_Information extends javax.swing.JFrame {
    int count = 10;
    boolean nameo, ageo, amounto, cityo, bgo, gendero;
    /**
     * Creates new form Donor_Information
     */
    public Donor_Information() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        db = new javax.swing.JButton();
        name = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        city = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        gender = new javax.swing.JComboBox<>();
        blood_grp = new javax.swing.JComboBox<>();
        amount = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(415, 325));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jLabel2.setText("Donor Information");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 200, 60);

        jLabel3.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLabel3.setText("Gender:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 120, 70, 20);

        jLabel4.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLabel4.setText("City:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 150, 60, 20);

        jLabel5.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLabel5.setText("Blood Group:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 180, 110, 20);

        jLabel6.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLabel6.setText("Amount:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 210, 70, 20);

        jLabel7.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLabel7.setText("Name:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 60, 60, 20);

        db.setText("Submit");
        db.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbActionPerformed(evt);
            }
        });
        getContentPane().add(db);
        db.setBounds(30, 240, 75, 22);

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name);
        name.setBounds(60, 60, 64, 22);

        age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageActionPerformed(evt);
            }
        });
        getContentPane().add(age);
        age.setBounds(40, 90, 64, 22);

        city.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityActionPerformed(evt);
            }
        });
        getContentPane().add(city);
        city.setBounds(40, 150, 71, 22);

        jLabel8.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLabel8.setText("Age:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 90, 60, 20);

        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Others" }));
        gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderActionPerformed(evt);
            }
        });
        getContentPane().add(gender);
        gender.setBounds(70, 120, 72, 22);

        blood_grp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AB+", "A+", "B+", "O+", "AB-", "A-", "B-", "O-" }));
        blood_grp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blood_grpActionPerformed(evt);
            }
        });
        getContentPane().add(blood_grp);
        blood_grp.setBounds(120, 180, 72, 22);

        amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountActionPerformed(evt);
            }
        });
        getContentPane().add(amount);
        amount.setBounds(70, 210, 71, 22);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\dhanu\\OneDrive\\Desktop\\images_ccexpress.jpeg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-470, 0, 870, 294);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbActionPerformed
        // TODO add your handling code here:
       
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/blood_bank_management","root","Dhanush1Vedant0");
            
            PreparedStatement insert_stmt=con.prepareStatement("INSERT INTO donor values(?,?,?,?,?,?,?)");
            insert_stmt.setInt(1, count); // primary key - donorID
            insert_stmt.setString(2, (String)gender.getSelectedItem()); // var gender of donor
            insert_stmt.setString(3, name.getText().toLowerCase()); // var name of donor
            insert_stmt.setInt(4, Integer.parseInt(age.getText())); // var age of donor
            insert_stmt.setString(5, city.getText().toLowerCase()); // var city of the donor
            insert_stmt.setString(6, (String)blood_grp.getSelectedItem()); // var blood group of the donor
            insert_stmt.setInt(7, Integer.parseInt(amount.getText())); // var amount of blood
            int i= insert_stmt.executeUpdate();  
            System.out.println(i+" records inserted");           
            String r_bg = (String)blood_grp.getSelectedItem();
            String r_city = city.getText().toLowerCase();
            int r_amount = Integer.parseInt(amount.getText());
            new Recipient_Results(count,r_bg, r_city, r_amount).setVisible(true);
            count++;
            dispose();
            con.close();
            
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_dbActionPerformed

    private void cityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityActionPerformed
        // TODO add your handling code here:
        cityo = true;
    }//GEN-LAST:event_cityActionPerformed

    private void amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountActionPerformed
        // TODO add your handling code here:
        amounto = true;
    }//GEN-LAST:event_amountActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
        nameo = true;
    }//GEN-LAST:event_nameActionPerformed

    private void ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageActionPerformed
        // TODO add your handling code here:
        ageo = true;
    }//GEN-LAST:event_ageActionPerformed

    private void genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderActionPerformed
        // TODO add your handling code here:
        gendero = true;
    }//GEN-LAST:event_genderActionPerformed

    private void blood_grpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blood_grpActionPerformed
        // TODO add your handling code here:
        bgo = true;
    }//GEN-LAST:event_blood_grpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Donor_Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Donor_Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Donor_Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Donor_Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Donor_Information().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField age;
    private javax.swing.JTextField amount;
    private javax.swing.JComboBox<String> blood_grp;
    private javax.swing.JTextField city;
    private javax.swing.JButton db;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField name;
    // End of variables declaration//GEN-END:variables
}
